/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export = {
  plugins: ['sppt'],
  rules: {
    'sppt/declaration-array-type': 'error',
    'sppt/no-console': 'error',
    'sppt/only-import-export': 'error',
  },
};
