/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

import recommended from './configs/recommended';
import defineType from './rules/define-type';

export = {
  configs: {
    recommended,
  },
  rules: {
    'define-type': defineType,
  },
};
