/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */

import recommended from './configs/recommended';
import declarationArrayType from './rules/declaration-array-type';
import defineType from './rules/define-type';

export = {
  configs: {
    recommended,
  },
  rules: {
    'declaration-array-type': declarationArrayType,
    'define-type': defineType,
  },
};
