name: release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release_npm_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - run: yarn install
      - run: yarn run build
      - run: npm version patch
        if: ${{ contains(github.event.head_commit.message, '[patch]')}}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - run: npm version minor
        if: ${{ contains(github.event.head_commit.message, '[minor]')}}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - run: npm version major
        if: ${{ contains(github.event.head_commit.message, '[minor]')}}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
