name: release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release_npm_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - run: npm ci
      - run: npm run build
      - run: npm version patch
        if: ${{ contains(github.event.push.head_commit.message, '[patch]')}}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - run: npm version minor
        if: ${{ contains(github.event.push.head_commit.message, '[minor]')}}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - run: npm version major
        if: ${{ contains(github.event.push.head_commit.message, '[minor]')}}
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - run: npm run publish
